name: tf-module-actions
on:
  - pull_request
permissions:
  contents: write
  pull-requests: write
  issues: write
  checks: write
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        working-dir: .,examples/01_default_configuration,examples/02_custom_schedule
        output-file: README.md
        output-method: inject
        git-push: "true"
    - name: Run Trivy vulnerability scanner in IaC mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'config'
        hide-progress: false
        format: 'sarif'
        output: 'trivy-config-results.sarif'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH,MEDIUM'
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-config-results.sarif'
        category: 'Trivy IaC Scan'
    - name: Run Trivy vulnerability scanner in Filesystem mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        hide-progress: false
        format: 'sarif'
        output: 'trivy-fs-results.sarif'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH,MEDIUM'
    - name: Upload Trivy Filesystem scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-fs-results.sarif'
        category: 'Trivy Filesystem Scan'
